## Autograd

Autograd is a core component of PyTorch that provides automatic differentiation for tensor operations. It enables gradient computation which is essential for training machine learning models using optimization algorithms like gradient descend.

In [2]:
import torch

In [3]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [4]:
y = x**2

In [5]:
y

tensor(9., grad_fn=<PowBackward0>)

In [6]:
y.backward()

In [7]:
x.grad

tensor(6.)

In [8]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)

In [9]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [10]:
z.backward()

In [13]:
x.grad

tensor(-5.4668)

In [16]:
x = torch.tensor([1, 2, 4], requires_grad=True, dtype=torch.float32)
x

tensor([1., 2., 4.], requires_grad=True)

In [17]:
y = (x**2).mean()

In [18]:
y.backward()

In [20]:
x.grad

tensor([0.6667, 1.3333, 2.6667])

In [22]:
## Clearning Gradients

x.grad.zero_()

tensor([0., 0., 0.])

In [23]:
# Closing gradient

with torch.no_grad():
    y = x ** 2