## Tensors in Python

Tensor is specialized multi-dimensional array designed for mathematical and computational efficiency.

1. No direction -> Scalar
2. 1 Direction -> vector/array
3. 2 Direction -> Matrix, image
4. 3 Direction -> Coloured Image (RGB)
5. 4D Tensors -> Batches of RGB images
6. 5D Tensors -> Video Data

Tensors enable efficient mathematical computations (addition, multiplication, dot product etc.) necessary for neural network operations.

In [1]:
import torch

print(torch.__version__)

2.8.0


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available! Using CPU")

GPU not available! Using CPU


In [4]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using Apple GPU with MPS")
else:
    device = torch.device("cpu")
    print("Using CPU")

Using Apple GPU with MPS


In [5]:
# using empty
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.rand(2, 3)

tensor([[0.8274, 0.5696, 0.9602],
        [0.6913, 0.4857, 0.9347]])

In [ ]:
torch.manual_seed(100) # For reproducabality
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1, 2, 3], [4, 5, 3]])

tensor([[1, 2, 3],
        [4, 5, 3]])

In [12]:
torch.eye(2, dtype=torch.int32)

tensor([[1, 0],
        [0, 1]], dtype=torch.int32)

In [ ]:
x = torch.tensor([[4, 5, 2], [6, 7, 8]])

x.shape # Rows x Columns

torch.Size([2, 3])

In [16]:
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [19]:
x.dtype # Get datatype

torch.int64

In [21]:
x.to(torch.float32) # Convert datatype

tensor([[4., 5., 2.],
        [6., 7., 8.]])

### Mathematical Operations

In [28]:
x = torch.rand(2, 2)

x + 11

tensor([[11.5277, 11.2472],
        [11.7909, 11.4235]])

In [29]:
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [30]:
y = torch.rand(2, 2)

In [31]:
x + y

tensor([[0.5446, 0.4681],
        [1.7444, 1.1299]])

In [33]:
x * y # element wise

tensor([[0.0089, 0.0546],
        [0.7541, 0.2992]])

In [36]:
torch.clamp(x, min=1, max=2)

tensor([[1., 1.],
        [1., 1.]])

In [39]:
data = torch.randint(size=(2, 3), low=1, high=10, dtype=torch.float32)
data

tensor([[1., 7., 5.],
        [4., 7., 2.]])

In [45]:
torch.mean(data)
torch.mean(data, dim=0) # mean by columns
torch.mean(data, dim=1) # mean by rows

tensor([4.3333, 4.3333])

### Matrix Operations

In [47]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[0, 4, 3],
        [8, 8, 3]])
tensor([[3, 5],
        [0, 6],
        [4, 0]])


In [48]:
torch.matmul(f, g)

tensor([[12, 24],
        [36, 88]])

In [49]:
torch.transpose(f, 0, 1)

tensor([[0, 8],
        [4, 8],
        [3, 3]])

In [53]:
mat = torch.rand(2, 2)
mat

tensor([[0.6868, 0.4920],
        [0.0748, 0.9605]])

In [ ]:
mat.det() # determinant

tensor(0.1471)

In [52]:
mat.inverse() # inverse

tensor([[ 3.7725, -0.3083],
        [-6.6623,  2.3470]])

In [54]:
torch.exp(mat)

tensor([[1.9873, 1.6356],
        [1.0777, 2.6130]])

In [57]:
mat.exp_() # use underscore for inplace operation

tensor([[ 7.2959,  5.1328],
        [ 2.9378, 13.6394]])

In [59]:
# Making Copy

mat2 = mat.clone()

In [60]:
print(id(mat2))
print(id(mat))

4582152688
4606280640


### Reshaping

In [61]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [63]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
import numpy as np

In [72]:
a = torch.tensor([1, 2, 3])

b = a.numpy()

print(type(b))

d = np.array([6, 7, 8])

c = torch.from_numpy(d)

print(c)

<class 'numpy.ndarray'>
tensor([6, 7, 8])
